// Generated by gencpp from file beginner_tutorials/change_stringResponse.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_CHANGE_STRINGRESPONSE_H
#define BEGINNER_TUTORIALS_MESSAGE_CHANGE_STRINGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct change_stringResponse_
{
  typedef change_stringResponse_<ContainerAllocator> Type;

  change_stringResponse_()
    : output_string()  {
    }
  change_stringResponse_(const ContainerAllocator& _alloc)
    : output_string(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _output_string_type;
  _output_string_type output_string;





  typedef boost::shared_ptr< ::beginner_tutorials::change_stringResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::change_stringResponse_<ContainerAllocator> const> ConstPtr;

}; // struct change_stringResponse_

typedef ::beginner_tutorials::change_stringResponse_<std::allocator<void> > change_stringResponse;

typedef boost::shared_ptr< ::beginner_tutorials::change_stringResponse > change_stringResponsePtr;
typedef boost::shared_ptr< ::beginner_tutorials::change_stringResponse const> change_stringResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::change_stringResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::change_stringResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::change_stringResponse_<ContainerAllocator1> & lhs, const ::beginner_tutorials::change_stringResponse_<ContainerAllocator2> & rhs)
{
  return lhs.output_string == rhs.output_string;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::change_stringResponse_<ContainerAllocator1> & lhs, const ::beginner_tutorials::change_stringResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::change_stringResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::change_stringResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::change_stringResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::change_stringResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::change_stringResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::change_stringResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::change_stringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "016361cdee7e84e8c448cca68658d16b";
  }

  static const char* value(const ::beginner_tutorials::change_stringResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x016361cdee7e84e8ULL;
  static const uint64_t static_value2 = 0xc448cca68658d16bULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::change_stringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/change_stringResponse";
  }

  static const char* value(const ::beginner_tutorials::change_stringResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::change_stringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string output_string\n"
"\n"
;
  }

  static const char* value(const ::beginner_tutorials::change_stringResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::change_stringResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output_string);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct change_stringResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::change_stringResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::change_stringResponse_<ContainerAllocator>& v)
  {
    s << indent << "output_string: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.output_string);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_CHANGE_STRINGRESPONSE_H
