// Generated by gencpp from file beginner_tutorials/change_stringRequest.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_CHANGE_STRINGREQUEST_H
#define BEGINNER_TUTORIALS_MESSAGE_CHANGE_STRINGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct change_stringRequest_
{
  typedef change_stringRequest_<ContainerAllocator> Type;

  change_stringRequest_()
    : input_string()  {
    }
  change_stringRequest_(const ContainerAllocator& _alloc)
    : input_string(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _input_string_type;
  _input_string_type input_string;





  typedef boost::shared_ptr< ::beginner_tutorials::change_stringRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::change_stringRequest_<ContainerAllocator> const> ConstPtr;

}; // struct change_stringRequest_

typedef ::beginner_tutorials::change_stringRequest_<std::allocator<void> > change_stringRequest;

typedef boost::shared_ptr< ::beginner_tutorials::change_stringRequest > change_stringRequestPtr;
typedef boost::shared_ptr< ::beginner_tutorials::change_stringRequest const> change_stringRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::change_stringRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::change_stringRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::change_stringRequest_<ContainerAllocator1> & lhs, const ::beginner_tutorials::change_stringRequest_<ContainerAllocator2> & rhs)
{
  return lhs.input_string == rhs.input_string;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::change_stringRequest_<ContainerAllocator1> & lhs, const ::beginner_tutorials::change_stringRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::change_stringRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::change_stringRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::change_stringRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::change_stringRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::change_stringRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::change_stringRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::change_stringRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6668f58127cd6f6b2b64175ee1268373";
  }

  static const char* value(const ::beginner_tutorials::change_stringRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6668f58127cd6f6bULL;
  static const uint64_t static_value2 = 0x2b64175ee1268373ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::change_stringRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/change_stringRequest";
  }

  static const char* value(const ::beginner_tutorials::change_stringRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::change_stringRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string input_string\n"
;
  }

  static const char* value(const ::beginner_tutorials::change_stringRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::change_stringRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input_string);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct change_stringRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::change_stringRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::change_stringRequest_<ContainerAllocator>& v)
  {
    s << indent << "input_string: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.input_string);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_CHANGE_STRINGREQUEST_H
